# Configuração da Base de Dados MySQL (a correr no Docker)
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/clubedesportivo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=password123

# O Hibernate (JPA) vai criar as tabelas automaticamente baseadas no teu código Java
spring.jpa.hibernate.ddl-auto=update

# Mostrar no terminal o SQL que o Java está a gerar
spring.jpa.show-sql=true